### ISSUE TITLE
Add the self-study guide to the list

### ISSUE THREAD

**Issue by raulfraile** [jmolivas/symfony-certification-guide#12]
Hey,

I just published the [self-study guide](https://leanpub.com/symfony-selfstudy) to prepare the certification and I was wondering if it could be added to this repository. If you let me know the section that fits best, I can open a PR.

Thanks!

**Comment by jmolivas** [comment]
@raulfraile there is a Book Section https://github.com/jmolivas/symfony-certification-guide#books 

I think that will be the best place to add. 

Feel free to send the PR
